---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yml
  # Get the environment variables from CircleCI and add to the EC2 instance
  roles:
    - configure-server
  # Get the environment variables from CircleCI and add to the EC2 instance
  environment: 
      ENVIRONMENT: production
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
      TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
      TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
