---

- name: "Configuration ansible play." 
  hosts: all # map with inventory.txt file# map with inventory.txt file
  user: ubuntu 
  become: true
  become_method: sudo
  become_user: root 
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

  roles:
    - configure-server
    # - configure-prometheus-node-exporter

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment: 
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"

