---

- name: "Configuration ansible play." 
  hosts: all # map with inventory.txt file
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root 
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy