---
  - name: "Update packages"
    become: true
    apt:
      update_cache: yes


  - name: "Upgrade apt packages"
    become: true
    apt:
      upgrade: yes


  - name: "Remove dependencies not required"
    become: true
    apt:
      autoremove: yes


  - name: "Install nodejs and npm"
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes


  - name: "Install n"
    become: true
    npm:
      name: n
      global: yes
      production: yes


  - name: "Install nodejs 13.8.0"
    become: true
    shell: n 13.8.0


  - name: "Install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present